--require ('core.configs.gruvbox')
--require ('core.configs.kanagawa')
--require ('core.configs.nord')
--require ('core.configs.tokyonight')
require ('core.configs.decay')
require ('core.configs.mason')
require ('core.configs.lualine')
require ('core.configs.tree')
require ('core.configs.telescope')
require ('core.configs.treesitter')
require ('core.configs.lsp')
require ('core.configs.autocomplete')
require ('core.configs.copilot')
require ('core.configs.colorizer')
require ('core.configs.null')
require ('core.configs.prettier')

